### ISSUE TITLE
DivaModLoader format download

### ISSUE THREAD

**Issue by RagdollClash** [Lyall/MegaMixPlusFix#2]
Even though the ASI loader method doesn't cause any conflicts, some people would prefer to have this as a mod and be able to manage it via [DivaModManager](https://github.com/TekkaGB/DivaModManager), [d4m](https://github.com/Brod8362/d4m), or [Rust4Diva](https://github.com/R3alCl0ud/Rust4Diva).

I have tested and verified that loading this via DivaModLoader is just as easy as providing a config.toml with the dll entry pointing to the ASI file.

```toml
enabled = true
dll = ["MegaMixPlusFix.asi"]

name = "MegaMixPlusFix"
version = "0.0.1"
date = "23.01.2025"
author = "Lyall"
```
